/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { AssetStatus } from './enums/assetStatus';

export type Asset = {
  /**
   * A unique identifier to represent the asset specifically on the exchange
   */
  assetId?: string;
  /**
   * A UUID to represent the asset (portable across other Coinbase systems)
   */
  assetUuid?: string;
  /**
   * The name of the asset
   */
  assetName?: string;
  status?: AssetStatus;
  /**
   * The haircut value applied to the asset when used as collateral
   */
  collateralWeight?: number;
  supportedNetworksEnabled?: boolean;
  minBorrowQty?: string;
  maxBorrowQty?: string;
  loanCollateralRequirementMultiplier?: number;
  ecosystemCollateralLimitBreached?: boolean;
  /**
   * The initial margin requirement for borrowing this asset
   */
  loanInitialMargin?: string;
  /**
   * The maximum amount of leverage a user can have on a loan of this asset
   */
  maxLoanLeverage?: string;
};
