/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type AssetNetwork = {
  /**
   * A unique identifier to represent the asset
   */
  assetId?: string;
  /**
   * A UUID to represent the asset
   */
  assetUuid?: string;
  /**
   * The name of the asset
   */
  assetName?: string;
  /**
   * A unique identifier representing the combination of the network and asset
   */
  networkArnId?: string;
  /**
   * The minimum amount of the asset that can be withdrawn from the network
   */
  minWithdrawalAmt?: string;
  /**
   * The maximum amount of the asset that can be withdrawn from the network
   */
  maxWithdrawalAmt?: string;
  /**
   * The number of confirmations required on the network for a transaction
   */
  networkConfirms?: number;
  /**
   * Number of seconds estimated to process a transaction on the network
   */
  processingTime?: number;
  /**
   * Indicates whether this is the default network for the asset
   */
  isDefault?: boolean;
  /**
   * The common name of the network
   */
  networkName?: string;
  /**
   * The human readable name of the network
   */
  displayName?: string;
};
