/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type CreatePortfolioPositionTransferRequest = {
  /**
   * Identifies the portfolio by UUID (e.g., `892e8c7c-e979-4cad-b61b-55a197932cf1`) or portfolio ID (e.g., `5189861793641175`) to transfer positions from
   */
  from: string;
  /**
   * Identifies the portfolio by UUID (e.g., `892e8c7c-e979-4cad-b61b-55a197932cf1`) or portfolio ID (e.g., `5189861793641175`) to transfer positions to
   */
  to: string;
  /**
   * Identifies the instrument by name (e.g., `BTC-PERP`), UUID (e.g., `291efb0f-2396-4d41-ad03-db3b2311cb2c`), or instrument ID (e.g., `1482439423963469`)
   */
  instrument: string;
  /**
   * The full or partial quantity of the position being transferred
   */
  quantity: string;
  /**
   * The side of the position being transferred, BUY or SELL
   */
  side: string;
};
