/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type IndexConstituent = {
  /**
   * The constituent asset pair symbol
   */
  symbol?: string;
  /**
   * The constituent name
   */
  name?: string;
  /**
   * The constituent rank order in the index
   */
  rank?: number;
  /**
   * The constituent market cap factor (or multiplier)
   */
  capFactor?: string;
  /**
   * The constituent amount
   */
  amount?: string;
  /**
   * The constituent total market cap
   */
  marketCap?: string;
  /**
   * The constituent market cap represented in the index
   */
  indexMarketCap?: string;
  /**
   * The weight of the constituent in the index
   */
  weight?: string;
  /**
   * The running weight of the constituent in the index
   */
  runningWeight?: string;
};
