/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type InstrumentQuote = {
  /**
   * The highest buy order price resting on the book
   */
  bestBidPrice?: string;
  /**
   * The total amount available at the best bid price
   */
  bestBidSize?: string;
  /**
   * The lowest sell order price resting on the book
   */
  bestAskPrice?: string;
  /**
   * The total amount available at the best ask price
   */
  bestAskSize?: string;
  /**
   * The price of the most recent trade
   */
  tradePrice?: string;
  /**
   * The size of the most recent trade
   */
  tradeQty?: string;
  /**
   * For perpetual futures only, the index price used for the funding process
   */
  indexPrice?: string;
  /**
   * The current mark price value used in risk and margin calculations
   */
  markPrice?: string;
  /**
   * The most recent settlement price value
   */
  settlementPrice?: string;
  /**
   * The max price the book allows buy orders to trade
   */
  limitUp?: string;
  /**
   * The min price the book allows sell orders to trade
   */
  limitDown?: string;
  /**
   * The predicted funding rate based on the current state of a rolling calculation
   */
  predictedFunding?: string;
  /**
   * The timestamp of the last quote update
   */
  timestamp?: Date;
};
