/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type ModifyOrderRequest = {
  /**
   * A unique identifier assigned by the client to the modified order. Must meet one of the following constraints:  - 18 characters long using all ASCII characters  - 20 characters long using alphanumeric characters and dash (-)  - 31 characters long using hexadecimal characters (0-9, a-f, lowercase and no preceding 0s)  - A UUID using standard hyphenation and all lowercase (e.g., 36a9d3ee-32b7-460e-979a-121735af4824)
   */
  clientOrderId: string;
  /**
   * Identifies the portfolio by UUID (e.g., `892e8c7c-e979-4cad-b61b-55a197932cf1`) or portfolio ID (e.g., `5189861793641175`); must match the original order referenced in the ID of the path
   */
  portfolio: string;
  /**
   * The max or min price limit in quote asset units to buy or sell at (respectively). Only used for limit and stop limit order types.
   */
  price?: string;
  /**
   * The market price that activates a stop order
   */
  stopPrice?: string;
  /**
   * The amount in base asset units
   */
  size?: string;
};
