/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type Pagination = {
  /**
   * The datetime from which to search (results are returned from `ref_datetime` in chronological order starting with the most recent). Uses ISO-8601 format (e.g., 2023-03-16T23:59:53Z)
   */
  refDatetime?: Date;
  /**
   * The number of results to return (defaults to 25 with a max supported value of 100)
   */
  resultLimit?: number;
  /**
   * The number of results from the beginning to skip past
   */
  resultOffset?: number;
};
