/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type PortfolioSummary = {
  /**
   * The total collateral value in USDC for the portfolio
   */
  collateral?: string;
  /**
   * The profit or loss of all open positions (resets to 0 after settlement)
   */
  unrealizedPnl?: string;
  /**
   * The profit or loss percentage of all open positions (resets to 0 after settlement)
   */
  unrealizedPnlPercent?: string;
  /**
   * The position value in USDC of all positions
   */
  positionNotional?: string;
  /**
   * The notional value of all open orders and positions
   */
  openPositionNotional?: string;
  /**
   * Accrued fees that haven\'t been paid yet
   */
  pendingFees?: string;
  /**
   * Total borrow amount in USDC (nets the USDC balance, position PNL, held USDC, accrued interest and rolling debt)
   */
  borrow?: string;
  /**
   * Interest charged for borrowed USDC balances
   */
  accruedInterest?: string;
  /**
   * Amount of settled transactions that haven\'t been paid
   */
  rollingDebt?: string;
  /**
   * The net balance available in the portfolio (collateral + unrealized_pnl - pending_fees - accrued_interest - rolling_debt)
   */
  balance?: string;
  /**
   * The amount of buying power available in the portfolio (balance - (open_position_notional * portfolio_initial_margin))
   */
  buyingPower?: string;
  /**
   * The weighted average of all the position\'s initial margin utilization
   */
  portfolioInitialMargin?: number;
  /**
   * The current margin level of the portfolio
   */
  portfolioCurrentMargin?: number;
  /**
   * The maintenance margin of the portfolio
   */
  portfolioMaintenanceMargin?: number;
  /**
   * The close out margin of the portfolio
   */
  portfolioCloseOutMargin?: number;
  /**
   * Indicates whether the portfolio is in process of liquidation
   */
  inLiquidation?: boolean;
  /**
   * The notional initial margin of the portfolio
   */
  portfolioInitialMarginNotional?: number;
  /**
   * The notional current margin level of the portfolio
   */
  portfolioCurrentMarginNotional?: number;
  /**
   * The notional maintenance margin of the portfolio
   */
  portfolioMaintenanceMarginNotional?: number;
  /**
   * The notional close out margin of the portfolio
   */
  portfolioCloseOutMarginNotional?: number;
  /**
   * The margin override value for the portfolio, indicating notional requirement to hold futures positions
   */
  marginOverride?: number;
  /**
   * The effective margin requirement value for the portfolio `(max(portfolio_initial_margin, margin_override))`
   */
  lockUpInitialMargin?: number;
  loanCollateralRequirement?: string;
  /**
   * The notional value of margin relief provided by position offsets
   */
  positionOffsetNotional?: number;
};
