/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type Portfolio = {
  /**
   * A unique identifier for the portfolio
   */
  portfolioId?: string;
  /**
   * A UUID for the portfolio
   */
  portfolioUuid?: string;
  /**
   * A human readable name for the portfolio
   */
  name?: string;
  /**
   * A user UUID for brokers that attribute a single user per portfolio
   */
  userUuid?: string;
  /**
   * The fee rate charged for order making liquidity
   */
  makerFeeRate?: string;
  /**
   * The fee rate charged for orders taking liquidity
   */
  takerFeeRate?: string;
  /**
   * Indicates if the portfolio has been locked from trading
   */
  tradingLock?: boolean;
  /**
   * Indicates whether or not the portfolio can borrow
   */
  borrowDisabled?: boolean;
  /**
   * Indicates if the portfolio is setup to take liquidation assignments
   */
  isLsp?: boolean;
  /**
   * Indicates if the portfolio is the account default portfolio
   */
  isDefault?: boolean;
  /**
   * Indicates if the cross collateral is enabled for the portfolio
   */
  crossCollateralEnabled?: boolean;
  /**
   * Indicates if pre-launch trading is enabled for the portfolio
   */
  preLaunchTradingEnabled?: boolean;
};
