/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type PortfolioPreviewLoanUpdateResult = {
  /**
   * The notional amount this loan contributes to the portfolio initial margin notional value
   */
  initialMarginContribution?: any | null;
  /**
   * The delta of notional amount this loan contributes to the portfolio initial margin notional value
   */
  initialMarginDelta?: any | null;
  /**
   * The weighted average of all initial margin utilization
   */
  portfolioInitialMargin?: string;
  /**
   * The notional initial margin of the portfolio
   */
  portfolioInitialMarginNotional?: string;
  /**
   * The notional collateral requirement to hold the loan
   */
  loanCollateralRequirement?: string;
  /**
   * The delta of notional collateral requirement to hold the loan
   */
  loanCollateralRequirementDelta?: string;
  /**
   * The total quantity of the asset borrowed by the portfolio
   */
  totalLoan?: string;
  /**
   * The delta of the total quantity of the asset borrowed by the portfolio
   */
  loanDelta?: string;
  /**
   * The maximum remaining amount of this asset that can be borrowed at this time
   */
  maxAvailable?: string;
  /**
   * The reason for the rejection of the loan preview request
   */
  rejectDetails?: string;
  /**
   * Indicates whether the requested loan preview could be executed
   */
  isValid?: boolean;
};
