/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type PortfolioUpdateLoanResult = {
  /**
   * The unique identifier of the portfolio
   */
  portfolioId?: string;
  /**
   * The unique identifier of the asset
   */
  assetId?: string;
  /**
   * The change in the loan amount
   */
  delta?: number;
  /**
   * The total quantity of the asset borrowed by the portfolio
   */
  total?: number;
  /**
   * The UUID of the asset
   */
  assetUuid?: string;
  /**
   * The UUID of the portfolio
   */
  portfolioUuid?: string;
};
