/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type PortfolioLoanInfoResult = {
  /**
   * The unique identifier of the portfolio the fill was executed under
   */
  portfolioId?: string;
  /**
   * The unique identifier of the asset
   */
  assetId?: string;
  /**
   * The UUID of the asset
   */
  assetUuid?: string;
  /**
   * Name of the asset
   */
  asset?: string;
  /**
   * The total quantity of the asset borrowed by the portfolio
   */
  totalLoan?: string;
  /**
   * The quantity of the asset automatically borrowed by the portfolio to cover USDC deficits
   */
  collateralBackedOverdraftLoan?: string;
  /**
   * The quantity of the asset borrowed by the portfolio upon explicit request
   */
  userRequestedLoan?: string;
  /**
   * The notional collateral requirement to hold the loan
   */
  collateralRequirement?: string;
  /**
   * The notional amount this loan contributes to the portfolio initial margin notional value
   */
  initialMarginContribution?: any | null;
  /**
   * The initial margin requirement of the loan
   */
  initialMarginRequirement?: any | null;
  /**
   * The annualized interest rate to hold the loan
   */
  currentInterestRate?: string;
  /**
   * The pending USDC charge for the loan that will be charged at UTC midnight
   */
  pendingInterestCharge?: string;
};
