/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type PreviewOrder = {
  /**
   * Returns whether or not the order form values are valid
   */
  isValid?: boolean;
  /**
   * The highest buy order price resting on the book
   */
  bestBidPrice?: string;
  /**
   * The lowest sell order price resting on the book
   */
  bestAskPrice?: string;
  /**
   * The current mark price value used in risk and margin calculations
   */
  markPrice?: string;
  /**
   * TBD
   */
  newOpenSize?: string;
  /**
   * TBD
   */
  openSizeDelta?: string;
  /**
   * TBD
   */
  newOpenNotional?: string;
  /**
   * TBD
   */
  openNotionalDelta?: string;
  /**
   * TBD
   */
  newTotalValueUsd?: string;
  /**
   * TBD
   */
  newOpenCostBasis?: string;
  /**
   * TBD
   */
  newMarginFraction?: string;
  /**
   * The estimated fee rate charged for order making liquidity
   */
  makerFeeEstimate?: string;
  /**
   * The estimated fee rate charged for orders taking liquidity
   */
  takerFeeEstimate?: string;
  /**
   * TBD
   */
  initialMargin?: string;
  /**
   * TBD
   */
  requiredMarginDelta?: string;
  /**
   * TBD
   */
  rejectReason?: string;
  /**
   * TBD
   */
  rejectDetails?: string;
};
