/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type Rankings = {
  /**
   * Ranking of the user based on the volume traded. If the user has not traded, the value returned is \"--\". If the instrumentType parameter is PERPETUAL_FUTURE then the user will see their rank if they are in the top 10, otherwise the value of `rank` will be 10+. If the instrumentType parameter is SPOT then the user will see their rank if they are in the top 3, otherwise the value of `rank` will be 3+.
   */
  rank?: string;
  /**
   * percentage of the total volume traded by this user
   */
  relativePercent?: string;
  /**
   * total volume traded by this user
   */
  volume?: string;
};
