/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type WithdrawRequest = {
  /**
   * Identifies the portfolio by UUID (e.g., `892e8c7c-e979-4cad-b61b-55a197932cf1`) or portfolio ID (e.g., `5189861793641175`)
   */
  portfolio: string;
  /**
   * Identifies the asset by name (e.g., `BTC`), UUID (e.g., `291efb0f-2396-4d41-ad03-db3b2311cb2c`), or asset ID (e.g., `1482439423963469`)
   */
  asset: string;
  /**
   * The amount of the asset being transferred
   */
  amount: string;
  /**
   * if true, deducts network fee from the portfolio, otherwise deduct fee from the withdrawal
   */
  addNetworkFeeToTotal: boolean;
  /**
   * Identifies the blockchain network (e.g., `networks/ethereum-mainnet/assets/313ef8a9-ae5a-5f2f-8a56-572c0e2a4d5a`)
   */
  networkArnId: string;
  /**
   * Crypto address being validated against
   */
  address: string;
  /**
   * a unique integer representing the withdrawal request
   */
  nonce?: number;
};
