/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * The time in force applied to an order. A Good Till Cancel (GTC) can last up to 30 days. An Immediate or Cancel (IOC) attempts to fill as much of the order as possible and/or cancels immediately when no resting orders meet or improve the order\'s price limit. A Fill or Kill (FOK) is canceled without filling if it does not completely fill immediately. This will not be populated for assignments
 */
export enum TimeInForce {
  Gtc = 'GTC',
  Ioc = 'IOC',
  Gtt = 'GTT',
  Fok = 'FOK',
}
